### ISSUE TITLE
immutable dependencies

### ISSUE THREAD

**Issue by djeeg** [actra-development-oss/redux-persist-transform-filter-immutable#6]
Would it possible to:

1. Remove dependencies -> immutable (peerDependencies should cover it)
https://github.com/actra-development-oss/redux-persist-transform-filter-immutable/blob/master/package.json#L34

2. Update peerDependencies to Allow immutablejs 4
eg https://github.com/rt2zz/redux-persist-transform-immutable/blob/master/package.json#L14

**Comment by actra-gschuster** [comment]
Sorry for the late reply, I published an updated release today including upgrades to immutable 4 and redux 4.
